version: 0.2
phases:
  pre_build:
    commands:
      -mvn clean install
      -echo Logging into Amazon ECR....
      -aws --version
      -$(aws ecr get-login --region $AWS_DEAULT_REGION --no-include-email)
      -REPOSITORY_URI = 602143770054.dkr.ecr.ap-south-1.amazonaws.com/awsdemo1-ecr-repo
      -COMMIT_HASH = $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      -IMAGE_TAG = build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Entered the build phase....
      - echo Build Started on'date'.....
      - echo Buildeing Dpcker Image......
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build Completed on 'date'
      - echo Pushing the docker image....
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:IMAGE_TAG
      - echo Writing image definition file .....
      - printf '[{"name":"awsdemo1","imageUri","%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - target/awsdemo1.jar
discarded-pahs: yes
